Repository outadoc/home-slide-android, pull requests merged in 2021-03, with the labels that each got.

#386 Fix group toggle
  common/src/main/java/fr/outadoc/homeslide/common/feature/grid/vm/EntityListViewModel.kt
  lib-homeassistant-api/src/main/java/fr/outadoc/homeslide/hassapi/model/entity/Group.kt
Labels: improvement

#388 feat(grid): add filter box in edit mode
  app/src/main/java/fr/outadoc/homeslide/app/feature/grid/ui/EntityGridFragment.kt
  app/src/main/res/layout/fragment_entity_grid.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  common/src/main/java/fr/outadoc/homeslide/common/feature/grid/vm/EntityListViewModel.kt
Labels: feature

#390 impr(grid): improve performance on main screen
  common/src/main/java/fr/outadoc/homeslide/common/feature/grid/vm/EntityListViewModel.kt
Labels: improvement

#391 release(1.6.4)
  buildSrc/src/main/kotlin/AppInfo.kt
  changelog/whatsnew-en-US
  changelog/whatsnew-fr-FR
Labels: release

#392 fix(grid): fix keyboard hide on filter action
  app/src/main/res/layout/fragment_entity_grid.xml
Labels: bug

#393 release(1.6.5)
  buildSrc/src/main/kotlin/AppInfo.kt
Labels: release

#397 fix(onboarding): fix crash when internal/external URLs are not present
  feature-onboarding/src/main/java/fr/outadoc/homeslide/app/onboarding/feature/host/HostSetupViewModel.kt
  lib-homeassistant-api/src/main/java/fr/outadoc/homeslide/hassapi/model/discovery/ValidatedDiscoveryInfo.kt
Labels: bug

#399 chore(licensing): attribute images to the correct copyright owner
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_infinity.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_invert_colors.xml
  app/src/main/res/drawable/ic_local_network.xml
  app/src/main/res/drawable/ic_lock_open.xml
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/drawable/ic_remote_network.xml
  app/src/main/res/drawable/ic_screen_lock.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_visibility_off.xml
  common/src/main/res/drawable/ic_analytics.xml
  common/src/main/res/drawable/ic_cat.xml
  common/src/main/res/drawable/ic_code.xml
  common/src/main/res/drawable/ic_home.xml
  common/src/main/res/drawable/ic_launcher_foreground.xml
  common/src/main/res/drawable/ic_open.xml
  feature-onboarding/src/main/res/drawable/avd_loading.xml
  feature-onboarding/src/main/res/drawable/ic_arrow_forward.xml
  feature-onboarding/src/main/res/drawable/ic_check.xml
  feature-onboarding/src/main/res/drawable/ic_error.xml
  feature-onboarding/src/main/res/drawable/ic_hass_logo.xml
Labels: chore

#400 release(1.6.6)
  buildSrc/src/main/kotlin/AppInfo.kt
  changelog/whatsnew-en-US
  changelog/whatsnew-fr-FR
Labels: release
